/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF, useAnimations } from "@react-three/drei";

import HolographicMaterial from "./HolographicMaterial";

export function Model({ holographicControls }, props) {
  const group = useRef();
  const { nodes, materials, animations } = useGLTF(
    "/assets/models/dji-mavic-2-pro/DJI-Mavic-Pro-2S-1k.glb"
  );
  const { actions } = useAnimations(animations, group);

  console.log("Actions:", actions);
  React.useEffect(() => {
    const speedMultiplier = 2; // Adjust this value to speed up the animations

    actions["PropsRotate"].play();
    actions["PropsRotate"].timeScale = speedMultiplier;

    actions["Wing8_FinalDJI_0.514Action.001"].play();
    actions["Wing8_FinalDJI_0.514Action.001"].timeScale = speedMultiplier;

    actions["Wing8_FinalDJI_0.435Action.002"].play();
    actions["Wing8_FinalDJI_0.435Action.002"].timeScale = speedMultiplier;

    actions["Wing8_FinalDJI_0.476Action"].play();
    actions["Wing8_FinalDJI_0.476Action"].timeScale = speedMultiplier;
  });

  const SpecialMaterial = () => (
    <HolographicMaterial {...holographicControls} />
  );

  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="Finalfbx">
          <group name="RootNode">
            <group name="Wing8">
              <mesh
                name="Wing8_FinalDJI_0012"
                castShadow
                receiveShadow
                geometry={nodes.Wing8_FinalDJI_0012.geometry}
                // material={materials["FinalDJI.006"]}
              >
                <SpecialMaterial />
              </mesh>
              <mesh
                name="Wing8_FinalDJI_0014"
                castShadow
                receiveShadow
                geometry={nodes.Wing8_FinalDJI_0014.geometry}
                // material={materials["FinalDJI.006"]}
              >
                <SpecialMaterial />
              </mesh>
              <mesh
                name="Wing8_FinalDJI_0015"
                castShadow
                receiveShadow
                geometry={nodes.Wing8_FinalDJI_0015.geometry}
                // material={materials["FinalDJI.006"]}
              >
                <SpecialMaterial />
              </mesh>
              <mesh
                name="Wing8_FinalDJI_0016"
                castShadow
                receiveShadow
                geometry={nodes.Wing8_FinalDJI_0016.geometry}
                // material={materials["FinalDJI.006"]}
              >
                <SpecialMaterial />
              </mesh>
              <mesh
                name="Wing8_FinalDJI_0017"
                castShadow
                receiveShadow
                geometry={nodes.Wing8_FinalDJI_0017.geometry}
                // material={materials["FinalDJI.006"]}
                position={[-0.016, 1.122, 0.631]}
              >
                <SpecialMaterial />
              </mesh>
              <mesh
                name="Wing8_FinalDJI_0018"
                castShadow
                receiveShadow
                geometry={nodes.Wing8_FinalDJI_0018.geometry}
                // material={materials["FinalDJI.006"]}
                position={[-0.016, 1.122, 0.631]}
              >
                <SpecialMaterial />
              </mesh>
              <mesh
                name="Wing8_FinalDJI_0019"
                castShadow
                receiveShadow
                geometry={nodes.Wing8_FinalDJI_0019.geometry}
                // material={materials["FinalDJI.006"]}
                position={[-0.016, 1.122, 0.631]}
              >
                <SpecialMaterial />
              </mesh>
              <mesh
                name="Wing8_FinalDJI_0020"
                castShadow
                receiveShadow
                geometry={nodes.Wing8_FinalDJI_0020.geometry}
                // material={materials["FinalDJI.006"]}
                position={[-0.016, 1.122, 0.631]}
              >
                <SpecialMaterial />
              </mesh>
              <mesh
                name="Wing8_FinalDJI_0021"
                castShadow
                receiveShadow
                geometry={nodes.Wing8_FinalDJI_0021.geometry}
                // material={materials["FinalDJI.006"]}
                position={[-0.016, 1.122, 0.631]}
              >
                <SpecialMaterial />
              </mesh>
              <mesh
                name="Wing8_FinalDJI_0023"
                castShadow
                receiveShadow
                geometry={nodes.Wing8_FinalDJI_0023.geometry}
                // material={materials["FinalDJI.006"]}
              >
                <SpecialMaterial />
              </mesh>
              <mesh
                name="Wing8_FinalDJI_0025"
                castShadow
                receiveShadow
                geometry={nodes.Wing8_FinalDJI_0025.geometry}
                // material={materials["FinalDJI.006"]}
              >
                <SpecialMaterial />
              </mesh>
              <mesh
                name="Wing8_FinalDJI_0026"
                castShadow
                receiveShadow
                geometry={nodes.Wing8_FinalDJI_0026.geometry}
                // material={materials["FinalDJI.006"]}
              >
                <SpecialMaterial />
              </mesh>
              <mesh
                name="Wing8_FinalDJI_0127"
                castShadow
                receiveShadow
                geometry={nodes.Wing8_FinalDJI_0127.geometry}
                // material={materials["FinalDJI.006"]}
              >
                <SpecialMaterial />
              </mesh>
              <mesh
                name="Wing8_FinalDJI_0128"
                castShadow
                receiveShadow
                geometry={nodes.Wing8_FinalDJI_0128.geometry}
                // material={materials["FinalDJI.006"]}
              >
                <SpecialMaterial />
              </mesh>
              <mesh
                name="Wing8_FinalDJI_0129"
                castShadow
                receiveShadow
                geometry={nodes.Wing8_FinalDJI_0129.geometry}
                // material={materials["FinalDJI.006"]}
              >
                <SpecialMaterial />
              </mesh>
              <mesh
                name="Wing8_FinalDJI_0130"
                castShadow
                receiveShadow
                geometry={nodes.Wing8_FinalDJI_0130.geometry}
                // material={materials["FinalDJI.006"]}
              >
                <SpecialMaterial />
              </mesh>
              <mesh
                name="Wing8_FinalDJI_0131"
                castShadow
                receiveShadow
                geometry={nodes.Wing8_FinalDJI_0131.geometry}
                // material={materials["FinalDJI.006"]}
              >
                <SpecialMaterial />
              </mesh>
              <mesh
                name="Wing8_FinalDJI_0132"
                castShadow
                receiveShadow
                geometry={nodes.Wing8_FinalDJI_0132.geometry}
                // material={materials["FinalDJI.006"]}
              >
                <SpecialMaterial />
              </mesh>
              <mesh
                name="Wing8_FinalDJI_0133"
                castShadow
                receiveShadow
                geometry={nodes.Wing8_FinalDJI_0133.geometry}
                // material={materials["FinalDJI.006"]}
              >
                <SpecialMaterial />
              </mesh>
              <mesh
                name="Wing8_FinalDJI_0134"
                castShadow
                receiveShadow
                geometry={nodes.Wing8_FinalDJI_0134.geometry}
                // material={materials["FinalDJI.006"]}
              >
                <SpecialMaterial />
              </mesh>
              <mesh
                name="Wing8_FinalDJI_0135"
                castShadow
                receiveShadow
                geometry={nodes.Wing8_FinalDJI_0135.geometry}
                // material={materials["FinalDJI.006"]}
              >
                <SpecialMaterial />
              </mesh>
              <mesh
                name="Wing8_FinalDJI_0136"
                castShadow
                receiveShadow
                geometry={nodes.Wing8_FinalDJI_0136.geometry}
                // material={materials["FinalDJI.006"]}
              >
                <SpecialMaterial />
              </mesh>
              <mesh
                name="Wing8_FinalDJI_0137"
                castShadow
                receiveShadow
                geometry={nodes.Wing8_FinalDJI_0137.geometry}
                // material={materials["FinalDJI.006"]}
              >
                <SpecialMaterial />
              </mesh>
              <mesh
                name="Wing8_FinalDJI_0139"
                castShadow
                receiveShadow
                geometry={nodes.Wing8_FinalDJI_0139.geometry}
                // material={materials["FinalDJI.006"]}
              >
                <SpecialMaterial />
              </mesh>
              <mesh
                name="Wing8_FinalDJI_0140"
                castShadow
                receiveShadow
                geometry={nodes.Wing8_FinalDJI_0140.geometry}
                // material={materials["FinalDJI.006"]}
              >
                <SpecialMaterial />
              </mesh>
              <mesh
                name="Wing8_FinalDJI_0141"
                castShadow
                receiveShadow
                geometry={nodes.Wing8_FinalDJI_0141.geometry}
                // material={materials["FinalDJI.006"]}
              >
                <SpecialMaterial />
              </mesh>
              <mesh
                name="Wing8_FinalDJI_0142"
                castShadow
                receiveShadow
                geometry={nodes.Wing8_FinalDJI_0142.geometry}
                // material={materials["FinalDJI.006"]}
              >
                <SpecialMaterial />
              </mesh>
              <mesh
                name="Wing8_FinalDJI_0143"
                castShadow
                receiveShadow
                geometry={nodes.Wing8_FinalDJI_0143.geometry}
                // material={materials["FinalDJI.006"]}
              >
                <SpecialMaterial />
              </mesh>
              <mesh
                name="Wing8_FinalDJI_0144"
                castShadow
                receiveShadow
                geometry={nodes.Wing8_FinalDJI_0144.geometry}
                // material={materials["FinalDJI.006"]}
              >
                <SpecialMaterial />
              </mesh>
              <mesh
                name="Wing8_FinalDJI_0145"
                castShadow
                receiveShadow
                geometry={nodes.Wing8_FinalDJI_0145.geometry}
                // material={materials["FinalDJI.006"]}
              >
                <SpecialMaterial />
              </mesh>
              <mesh
                name="Wing8_FinalDJI_0146"
                castShadow
                receiveShadow
                geometry={nodes.Wing8_FinalDJI_0146.geometry}
                // material={materials["FinalDJI.006"]}
              >
                <SpecialMaterial />
              </mesh>
              <mesh
                name="Wing8_FinalDJI_0147"
                castShadow
                receiveShadow
                geometry={nodes.Wing8_FinalDJI_0147.geometry}
                // material={materials["FinalDJI.006"]}
              >
                <SpecialMaterial />
              </mesh>
              <mesh
                name="Wing8_FinalDJI_0148"
                castShadow
                receiveShadow
                geometry={nodes.Wing8_FinalDJI_0148.geometry}
                // material={materials["FinalDJI.006"]}
              >
                <SpecialMaterial />
              </mesh>
              <mesh
                name="Wing8_FinalDJI_0149"
                castShadow
                receiveShadow
                geometry={nodes.Wing8_FinalDJI_0149.geometry}
                // material={materials["FinalDJI.006"]}
              >
                <SpecialMaterial />
              </mesh>
              <mesh
                name="Wing8_FinalDJI_0150"
                castShadow
                receiveShadow
                geometry={nodes.Wing8_FinalDJI_0150.geometry}
                // material={materials["FinalDJI.006"]}
              >
                <SpecialMaterial />
              </mesh>
              <mesh
                name="Wing8_FinalDJI_0151"
                castShadow
                receiveShadow
                geometry={nodes.Wing8_FinalDJI_0151.geometry}
                // material={materials["FinalDJI.006"]}
              >
                <SpecialMaterial />
              </mesh>
              <mesh
                name="Wing8_FinalDJI_0152"
                castShadow
                receiveShadow
                geometry={nodes.Wing8_FinalDJI_0152.geometry}
                // material={materials["FinalDJI.006"]}
              >
                <SpecialMaterial />
              </mesh>
              <mesh
                name="Wing8_FinalDJI_0153"
                castShadow
                receiveShadow
                geometry={nodes.Wing8_FinalDJI_0153.geometry}
                // material={materials["FinalDJI.006"]}
              >
                <SpecialMaterial />
              </mesh>
              <mesh
                name="Wing8_FinalDJI_0154"
                castShadow
                receiveShadow
                geometry={nodes.Wing8_FinalDJI_0154.geometry}
                // material={materials["FinalDJI.006"]}
              >
                <SpecialMaterial />
              </mesh>
              <mesh
                name="Wing8_FinalDJI_0155"
                castShadow
                receiveShadow
                geometry={nodes.Wing8_FinalDJI_0155.geometry}
                // material={materials["FinalDJI.006"]}
              >
                <SpecialMaterial />
              </mesh>
              <mesh
                name="Wing8_FinalDJI_0156"
                castShadow
                receiveShadow
                geometry={nodes.Wing8_FinalDJI_0156.geometry}
                // material={materials["FinalDJI.006"]}
              >
                <SpecialMaterial />
              </mesh>
              <mesh
                name="Wing8_FinalDJI_0157"
                castShadow
                receiveShadow
                geometry={nodes.Wing8_FinalDJI_0157.geometry}
                // material={materials["FinalDJI.006"]}
              >
                <SpecialMaterial />
              </mesh>
              <mesh
                name="Wing8_FinalDJI_0158"
                castShadow
                receiveShadow
                geometry={nodes.Wing8_FinalDJI_0158.geometry}
                // material={materials["FinalDJI.006"]}
              >
                <SpecialMaterial />
              </mesh>
              <mesh
                name="Wing8_FinalDJI_0159"
                castShadow
                receiveShadow
                geometry={nodes.Wing8_FinalDJI_0159.geometry}
                // material={materials["FinalDJI.006"]}
              >
                <SpecialMaterial />
              </mesh>
              <mesh
                name="Wing8_FinalDJI_0160"
                castShadow
                receiveShadow
                geometry={nodes.Wing8_FinalDJI_0160.geometry}
                // material={materials["FinalDJI.006"]}
              >
                <SpecialMaterial />
              </mesh>
              <mesh
                name="Wing8_FinalDJI_0161"
                castShadow
                receiveShadow
                geometry={nodes.Wing8_FinalDJI_0161.geometry}
                // material={materials["FinalDJI.006"]}
              >
                <SpecialMaterial />
              </mesh>
              <mesh
                name="Wing8_FinalDJI_0162"
                castShadow
                receiveShadow
                geometry={nodes.Wing8_FinalDJI_0162.geometry}
                // material={materials["FinalDJI.006"]}
              >
                <SpecialMaterial />
              </mesh>
              <mesh
                name="Wing8_FinalDJI_0163"
                castShadow
                receiveShadow
                geometry={nodes.Wing8_FinalDJI_0163.geometry}
                // material={materials["FinalDJI.006"]}
              >
                <SpecialMaterial />
              </mesh>
              <mesh
                name="Wing8_FinalDJI_0164"
                castShadow
                receiveShadow
                geometry={nodes.Wing8_FinalDJI_0164.geometry}
                // material={materials["FinalDJI.006"]}
              >
                <SpecialMaterial />
              </mesh>
              <mesh
                name="Wing8_FinalDJI_0165"
                castShadow
                receiveShadow
                geometry={nodes.Wing8_FinalDJI_0165.geometry}
                // material={materials["FinalDJI.006"]}
              >
                <SpecialMaterial />
              </mesh>
              <mesh
                name="Wing8_FinalDJI_0166"
                castShadow
                receiveShadow
                geometry={nodes.Wing8_FinalDJI_0166.geometry}
                // material={materials["FinalDJI.006"]}
              >
                <SpecialMaterial />
              </mesh>
              <mesh
                name="Wing8_FinalDJI_0167"
                castShadow
                receiveShadow
                geometry={nodes.Wing8_FinalDJI_0167.geometry}
                // material={materials["FinalDJI.006"]}
              >
                <SpecialMaterial />
              </mesh>
              <mesh
                name="Wing8_FinalDJI_0168"
                castShadow
                receiveShadow
                geometry={nodes.Wing8_FinalDJI_0168.geometry}
                // material={materials["FinalDJI.006"]}
              >
                <SpecialMaterial />
              </mesh>
              <mesh
                name="Wing8_FinalDJI_0169"
                castShadow
                receiveShadow
                geometry={nodes.Wing8_FinalDJI_0169.geometry}
                // material={materials["FinalDJI.006"]}
              >
                <SpecialMaterial />
              </mesh>
              <mesh
                name="Wing8_FinalDJI_0170"
                castShadow
                receiveShadow
                geometry={nodes.Wing8_FinalDJI_0170.geometry}
                // material={materials["FinalDJI.006"]}
              >
                <SpecialMaterial />
              </mesh>
              <mesh
                name="Wing8_FinalDJI_0171"
                castShadow
                receiveShadow
                geometry={nodes.Wing8_FinalDJI_0171.geometry}
                // material={materials["FinalDJI.006"]}
              >
                <SpecialMaterial />
              </mesh>
              <mesh
                name="Wing8_FinalDJI_0172"
                castShadow
                receiveShadow
                geometry={nodes.Wing8_FinalDJI_0172.geometry}
                // material={materials["FinalDJI.006"]}
              >
                <SpecialMaterial />
              </mesh>
              <mesh
                name="Wing8_FinalDJI_0173"
                castShadow
                receiveShadow
                geometry={nodes.Wing8_FinalDJI_0173.geometry}
                // material={materials["FinalDJI.006"]}
              >
                <SpecialMaterial />
              </mesh>
              <mesh
                name="Wing8_FinalDJI_0174"
                castShadow
                receiveShadow
                geometry={nodes.Wing8_FinalDJI_0174.geometry}
                // material={materials["FinalDJI.006"]}
              >
                <SpecialMaterial />
              </mesh>
              <mesh
                name="Wing8_FinalDJI_0175"
                castShadow
                receiveShadow
                geometry={nodes.Wing8_FinalDJI_0175.geometry}
                // material={materials["FinalDJI.006"]}
              >
                <SpecialMaterial />
              </mesh>
              <mesh
                name="Wing8_FinalDJI_0176"
                castShadow
                receiveShadow
                geometry={nodes.Wing8_FinalDJI_0176.geometry}
                // material={materials["FinalDJI.006"]}
              >
                <SpecialMaterial />
              </mesh>
              <mesh
                name="Wing8_FinalDJI_0177"
                castShadow
                receiveShadow
                geometry={nodes.Wing8_FinalDJI_0177.geometry}
                // material={materials["FinalDJI.006"]}
              >
                <SpecialMaterial />
              </mesh>
              <mesh
                name="Wing8_FinalDJI_0178"
                castShadow
                receiveShadow
                geometry={nodes.Wing8_FinalDJI_0178.geometry}
                // material={materials["FinalDJI.006"]}
              >
                <SpecialMaterial />
              </mesh>
              <mesh
                name="Wing8_FinalDJI_0179"
                castShadow
                receiveShadow
                geometry={nodes.Wing8_FinalDJI_0179.geometry}
                // material={materials["FinalDJI.006"]}
              >
                <SpecialMaterial />
              </mesh>
              <mesh
                name="Wing8_FinalDJI_0180"
                castShadow
                receiveShadow
                geometry={nodes.Wing8_FinalDJI_0180.geometry}
                // material={materials["FinalDJI.006"]}
              >
                <SpecialMaterial />
              </mesh>
              <mesh
                name="Wing8_FinalDJI_0181"
                castShadow
                receiveShadow
                geometry={nodes.Wing8_FinalDJI_0181.geometry}
                // material={materials["FinalDJI.006"]}
              >
                <SpecialMaterial />
              </mesh>
              <mesh
                name="Wing8_FinalDJI_0182"
                castShadow
                receiveShadow
                geometry={nodes.Wing8_FinalDJI_0182.geometry}
                // material={materials["FinalDJI.006"]}
              >
                <SpecialMaterial />
              </mesh>
              <mesh
                name="Wing8_FinalDJI_0183"
                castShadow
                receiveShadow
                geometry={nodes.Wing8_FinalDJI_0183.geometry}
                // material={materials["FinalDJI.006"]}
              >
                <SpecialMaterial />
              </mesh>
              <mesh
                name="Wing8_FinalDJI_0184"
                castShadow
                receiveShadow
                geometry={nodes.Wing8_FinalDJI_0184.geometry}
                // material={materials["FinalDJI.006"]}
              >
                <SpecialMaterial />
              </mesh>
              <mesh
                name="Wing8_FinalDJI_0185"
                castShadow
                receiveShadow
                geometry={nodes.Wing8_FinalDJI_0185.geometry}
                // material={materials["FinalDJI.006"]}
              >
                <SpecialMaterial />
              </mesh>
              <mesh
                name="Wing8_FinalDJI_0186"
                castShadow
                receiveShadow
                geometry={nodes.Wing8_FinalDJI_0186.geometry}
                // material={materials["FinalDJI.006"]}
              >
                <SpecialMaterial />
              </mesh>
              <mesh
                name="Wing8_FinalDJI_0187"
                castShadow
                receiveShadow
                geometry={nodes.Wing8_FinalDJI_0187.geometry}
                // material={materials["FinalDJI.006"]}
              >
                <SpecialMaterial />
              </mesh>
              <mesh
                name="Wing8_FinalDJI_0188"
                castShadow
                receiveShadow
                geometry={nodes.Wing8_FinalDJI_0188.geometry}
                // material={materials["FinalDJI.006"]}
              >
                <SpecialMaterial />
              </mesh>
              <mesh
                name="Wing8_FinalDJI_0189"
                castShadow
                receiveShadow
                geometry={nodes.Wing8_FinalDJI_0189.geometry}
                // material={materials["FinalDJI.006"]}
              >
                <SpecialMaterial />
              </mesh>
              <mesh
                name="Wing8_FinalDJI_0190"
                castShadow
                receiveShadow
                geometry={nodes.Wing8_FinalDJI_0190.geometry}
                // material={materials["FinalDJI.006"]}
              >
                <SpecialMaterial />
              </mesh>
              <mesh
                name="Wing8_FinalDJI_0191"
                castShadow
                receiveShadow
                geometry={nodes.Wing8_FinalDJI_0191.geometry}
                // material={materials["FinalDJI.006"]}
              >
                <SpecialMaterial />
              </mesh>
              <mesh
                name="Wing8_FinalDJI_0192"
                castShadow
                receiveShadow
                geometry={nodes.Wing8_FinalDJI_0192.geometry}
                // material={materials["FinalDJI.006"]}
              >
                <SpecialMaterial />
              </mesh>
              <mesh
                name="Wing8_FinalDJI_0193"
                castShadow
                receiveShadow
                geometry={nodes.Wing8_FinalDJI_0193.geometry}
                // material={materials["FinalDJI.006"]}
              >
                <SpecialMaterial />
              </mesh>
              <mesh
                name="Wing8_FinalDJI_0194"
                castShadow
                receiveShadow
                geometry={nodes.Wing8_FinalDJI_0194.geometry}
                // material={materials["FinalDJI.006"]}
              >
                <SpecialMaterial />
              </mesh>
              <mesh
                name="Wing8_FinalDJI_0195"
                castShadow
                receiveShadow
                geometry={nodes.Wing8_FinalDJI_0195.geometry}
                // material={materials["FinalDJI.006"]}
              >
                <SpecialMaterial />
              </mesh>
              <mesh
                name="Wing8_FinalDJI_0196"
                castShadow
                receiveShadow
                geometry={nodes.Wing8_FinalDJI_0196.geometry}
                // material={materials["FinalDJI.006"]}
              >
                <SpecialMaterial />
              </mesh>
              <mesh
                name="Wing8_FinalDJI_0197"
                castShadow
                receiveShadow
                geometry={nodes.Wing8_FinalDJI_0197.geometry}
                // material={materials["FinalDJI.006"]}
                position={[-0.016, 1.122, 0.631]}
              >
                <SpecialMaterial />
              </mesh>
              <mesh
                name="Wing8_FinalDJI_0198"
                castShadow
                receiveShadow
                geometry={nodes.Wing8_FinalDJI_0198.geometry}
                // material={materials["FinalDJI.006"]}
                position={[-0.016, 1.122, 0.631]}
              >
                <SpecialMaterial />
              </mesh>
              <mesh
                name="Wing8_FinalDJI_0199"
                castShadow
                receiveShadow
                geometry={nodes.Wing8_FinalDJI_0199.geometry}
                // material={materials["FinalDJI.006"]}
                position={[-0.016, 1.122, 0.631]}
              >
                <SpecialMaterial />
              </mesh>
              <mesh
                name="Wing8_FinalDJI_0200"
                castShadow
                receiveShadow
                geometry={nodes.Wing8_FinalDJI_0200.geometry}
                // material={materials["FinalDJI.006"]}
                position={[-0.016, 1.122, 0.631]}
              >
                <SpecialMaterial />
              </mesh>
              <mesh
                name="Wing8_FinalDJI_0201"
                castShadow
                receiveShadow
                geometry={nodes.Wing8_FinalDJI_0201.geometry}
                // material={materials["FinalDJI.006"]}
                position={[-0.016, 1.122, 0.631]}
              >
                <SpecialMaterial />
              </mesh>
              <mesh
                name="Wing8_FinalDJI_0202"
                castShadow
                receiveShadow
                geometry={nodes.Wing8_FinalDJI_0202.geometry}
                // material={materials["FinalDJI.006"]}
                position={[-0.016, 1.122, 0.631]}
              >
                <SpecialMaterial />
              </mesh>
              <mesh
                name="Wing8_FinalDJI_0203"
                castShadow
                receiveShadow
                geometry={nodes.Wing8_FinalDJI_0203.geometry}
                // material={materials["FinalDJI.006"]}
                position={[-0.016, 1.122, 0.631]}
              >
                <SpecialMaterial />
              </mesh>
              <mesh
                name="Wing8_FinalDJI_0204"
                castShadow
                receiveShadow
                geometry={nodes.Wing8_FinalDJI_0204.geometry}
                // material={materials["FinalDJI.006"]}
                position={[-0.016, 1.122, 0.631]}
              >
                <SpecialMaterial />
              </mesh>
              <mesh
                name="Wing8_FinalDJI_0205"
                castShadow
                receiveShadow
                geometry={nodes.Wing8_FinalDJI_0205.geometry}
                // material={materials["FinalDJI.006"]}
                position={[-0.016, 1.122, 0.631]}
              >
                <SpecialMaterial />
              </mesh>
              <mesh
                name="Wing8_FinalDJI_0206"
                castShadow
                receiveShadow
                geometry={nodes.Wing8_FinalDJI_0206.geometry}
                // material={materials["FinalDJI.006"]}
                position={[-0.016, 1.122, 0.631]}
              >
                <SpecialMaterial />
              </mesh>
              <mesh
                name="Wing8_FinalDJI_0207"
                castShadow
                receiveShadow
                geometry={nodes.Wing8_FinalDJI_0207.geometry}
                // material={materials["FinalDJI.006"]}
                position={[-0.016, 1.122, 0.631]}
              >
                <SpecialMaterial />
              </mesh>
              <mesh
                name="Wing8_FinalDJI_0208"
                castShadow
                receiveShadow
                geometry={nodes.Wing8_FinalDJI_0208.geometry}
                // material={materials["FinalDJI.006"]}
                position={[-0.016, 1.122, 0.631]}
              >
                <SpecialMaterial />
              </mesh>
              <mesh
                name="Wing8_FinalDJI_0209"
                castShadow
                receiveShadow
                geometry={nodes.Wing8_FinalDJI_0209.geometry}
                // material={materials["FinalDJI.006"]}
                position={[-0.016, 1.122, 0.631]}
              >
                <SpecialMaterial />
              </mesh>
              <mesh
                name="Wing8_FinalDJI_0210"
                castShadow
                receiveShadow
                geometry={nodes.Wing8_FinalDJI_0210.geometry}
                // material={materials["FinalDJI.006"]}
                position={[-0.016, 1.122, 0.631]}
              >
                <SpecialMaterial />
              </mesh>
              <mesh
                name="Wing8_FinalDJI_0211"
                castShadow
                receiveShadow
                geometry={nodes.Wing8_FinalDJI_0211.geometry}
                // material={materials["FinalDJI.006"]}
                position={[-0.016, 1.122, 0.631]}
              >
                <SpecialMaterial />
              </mesh>
              <mesh
                name="Wing8_FinalDJI_0212"
                castShadow
                receiveShadow
                geometry={nodes.Wing8_FinalDJI_0212.geometry}
                // material={materials["FinalDJI.006"]}
                position={[-0.016, 1.122, 0.631]}
              >
                <SpecialMaterial />
              </mesh>
              <mesh
                name="Wing8_FinalDJI_0213"
                castShadow
                receiveShadow
                geometry={nodes.Wing8_FinalDJI_0213.geometry}
                // material={materials["FinalDJI.006"]}
                position={[-0.016, 1.122, 0.631]}
              >
                <SpecialMaterial />
              </mesh>
              <mesh
                name="Wing8_FinalDJI_0214"
                castShadow
                receiveShadow
                geometry={nodes.Wing8_FinalDJI_0214.geometry}
                // material={materials["FinalDJI.006"]}
                position={[-0.016, 1.122, 0.631]}
              >
                <SpecialMaterial />
              </mesh>
              <mesh
                name="Wing8_FinalDJI_0215"
                castShadow
                receiveShadow
                geometry={nodes.Wing8_FinalDJI_0215.geometry}
                // material={materials["FinalDJI.006"]}
                position={[-0.017, 0.849, 0.737]}
              >
                <SpecialMaterial />
              </mesh>
              <mesh
                name="Wing8_FinalDJI_0225"
                castShadow
                receiveShadow
                geometry={nodes.Wing8_FinalDJI_0225.geometry}
                // material={materials["FinalDJI.006"]}
                position={[-0.016, 1.122, 0.631]}
              >
                <SpecialMaterial />
              </mesh>
              <mesh
                name="Wing8_FinalDJI_0227"
                castShadow
                receiveShadow
                geometry={nodes.Wing8_FinalDJI_0227.geometry}
                // material={materials["FinalDJI.006"]}
                position={[-0.016, 1.122, 0.631]}
              >
                <SpecialMaterial />
              </mesh>
              <mesh
                name="Wing8_FinalDJI_0228"
                castShadow
                receiveShadow
                geometry={nodes.Wing8_FinalDJI_0228.geometry}
                // material={materials["FinalDJI.006"]}
                position={[-0.016, 1.122, 0.631]}
              >
                <SpecialMaterial />
              </mesh>
              <mesh
                name="Wing8_FinalDJI_0233"
                castShadow
                receiveShadow
                geometry={nodes.Wing8_FinalDJI_0233.geometry}
                // material={materials["FinalDJI.006"]}
                position={[-0.016, 1.122, 0.631]}
              >
                <SpecialMaterial />
              </mesh>
              <mesh
                name="Wing8_FinalDJI_0234"
                castShadow
                receiveShadow
                geometry={nodes.Wing8_FinalDJI_0234.geometry}
                // material={materials["FinalDJI.006"]}
                position={[-0.016, 1.122, 0.631]}
              >
                <SpecialMaterial />
              </mesh>
              <mesh
                name="Wing8_FinalDJI_0235"
                castShadow
                receiveShadow
                geometry={nodes.Wing8_FinalDJI_0235.geometry}
                // material={materials["FinalDJI.006"]}
                position={[-0.016, 1.122, 0.631]}
              >
                <SpecialMaterial />
              </mesh>
              <mesh
                name="Wing8_FinalDJI_0236"
                castShadow
                receiveShadow
                geometry={nodes.Wing8_FinalDJI_0236.geometry}
                // material={materials["FinalDJI.006"]}
                position={[-0.016, 1.122, 0.631]}
              >
                <SpecialMaterial />
              </mesh>
              <mesh
                name="Wing8_FinalDJI_0237"
                castShadow
                receiveShadow
                geometry={nodes.Wing8_FinalDJI_0237.geometry}
                // material={materials["FinalDJI.006"]}
                position={[-0.016, 1.122, 0.631]}
              >
                <SpecialMaterial />
              </mesh>
              <mesh
                name="Wing8_FinalDJI_0238"
                castShadow
                receiveShadow
                geometry={nodes.Wing8_FinalDJI_0238.geometry}
                // material={materials["FinalDJI.006"]}
                position={[-0.016, 1.122, 0.631]}
              >
                <SpecialMaterial />
              </mesh>
              <mesh
                name="Wing8_FinalDJI_0239"
                castShadow
                receiveShadow
                geometry={nodes.Wing8_FinalDJI_0239.geometry}
                // material={materials["FinalDJI.006"]}
                position={[-0.016, 1.122, 0.631]}
              >
                <SpecialMaterial />
              </mesh>
              <mesh
                name="Wing8_FinalDJI_0240"
                castShadow
                receiveShadow
                geometry={nodes.Wing8_FinalDJI_0240.geometry}
                // material={materials["FinalDJI.006"]}
                position={[-0.016, 1.122, 0.631]}
              >
                <SpecialMaterial />
              </mesh>
              <mesh
                name="Wing8_FinalDJI_0241"
                castShadow
                receiveShadow
                geometry={nodes.Wing8_FinalDJI_0241.geometry}
                // material={materials["FinalDJI.006"]}
                position={[-0.016, 1.122, 0.631]}
              >
                <SpecialMaterial />
              </mesh>
              <mesh
                name="Wing8_FinalDJI_0242"
                castShadow
                receiveShadow
                geometry={nodes.Wing8_FinalDJI_0242.geometry}
                // material={materials["FinalDJI.006"]}
                position={[-0.016, 1.122, 0.631]}
              >
                <SpecialMaterial />
              </mesh>
              <mesh
                name="Wing8_FinalDJI_0243"
                castShadow
                receiveShadow
                geometry={nodes.Wing8_FinalDJI_0243.geometry}
                // material={materials["FinalDJI.006"]}
                position={[-0.016, 1.122, 0.631]}
              >
                <SpecialMaterial />
              </mesh>
              <mesh
                name="Wing8_FinalDJI_0244"
                castShadow
                receiveShadow
                geometry={nodes.Wing8_FinalDJI_0244.geometry}
                // material={materials["FinalDJI.006"]}
                position={[-0.016, 1.122, 0.631]}
              >
                <SpecialMaterial />
              </mesh>
              <mesh
                name="Wing8_FinalDJI_0245"
                castShadow
                receiveShadow
                geometry={nodes.Wing8_FinalDJI_0245.geometry}
                // material={materials["FinalDJI.006"]}
                position={[-0.016, 1.122, 0.631]}
              >
                <SpecialMaterial />
              </mesh>
              <mesh
                name="Wing8_FinalDJI_0250"
                castShadow
                receiveShadow
                geometry={nodes.Wing8_FinalDJI_0250.geometry}
                // material={materials["FinalDJI.006"]}
                position={[-0.016, 1.122, 0.631]}
              >
                <SpecialMaterial />
              </mesh>
              <mesh
                name="Wing8_FinalDJI_0251"
                castShadow
                receiveShadow
                geometry={nodes.Wing8_FinalDJI_0251.geometry}
                // material={materials["FinalDJI.006"]}
                position={[-0.016, 1.122, 0.631]}
              >
                <SpecialMaterial />
              </mesh>
              <mesh
                name="Wing8_FinalDJI_0252"
                castShadow
                receiveShadow
                geometry={nodes.Wing8_FinalDJI_0252.geometry}
                // material={materials["FinalDJI.006"]}
                position={[-0.016, 1.122, 0.631]}
              >
                <SpecialMaterial />
              </mesh>
              <mesh
                name="Wing8_FinalDJI_0254"
                castShadow
                receiveShadow
                geometry={nodes.Wing8_FinalDJI_0254.geometry}
                // material={materials["FinalDJI.006"]}
                position={[-0.016, 1.122, 0.631]}
              >
                <SpecialMaterial />
              </mesh>
              <mesh
                name="Wing8_FinalDJI_0255"
                castShadow
                receiveShadow
                geometry={nodes.Wing8_FinalDJI_0255.geometry}
                // material={materials["FinalDJI.006"]}
                position={[-0.016, 1.122, 0.631]}
              >
                <SpecialMaterial />
              </mesh>
              <mesh
                name="Wing8_FinalDJI_0256"
                castShadow
                receiveShadow
                geometry={nodes.Wing8_FinalDJI_0256.geometry}
                // material={materials["FinalDJI.006"]}
                position={[-0.016, 1.122, 0.631]}
              >
                <SpecialMaterial />
              </mesh>
              <mesh
                name="Wing8_FinalDJI_0257"
                castShadow
                receiveShadow
                geometry={nodes.Wing8_FinalDJI_0257.geometry}
                // material={materials["FinalDJI.006"]}
                position={[-0.016, 1.122, 0.631]}
              >
                <SpecialMaterial />
              </mesh>
              <mesh
                name="Wing8_FinalDJI_0258"
                castShadow
                receiveShadow
                geometry={nodes.Wing8_FinalDJI_0258.geometry}
                // material={materials["FinalDJI.006"]}
                position={[-0.016, 1.122, 0.631]}
              >
                <SpecialMaterial />
              </mesh>
              <mesh
                name="Wing8_FinalDJI_0259"
                castShadow
                receiveShadow
                geometry={nodes.Wing8_FinalDJI_0259.geometry}
                // material={materials["FinalDJI.006"]}
                position={[-0.016, 1.122, 0.631]}
              >
                <SpecialMaterial />
              </mesh>
              <mesh
                name="Wing8_FinalDJI_0260"
                castShadow
                receiveShadow
                geometry={nodes.Wing8_FinalDJI_0260.geometry}
                // material={materials["FinalDJI.006"]}
                position={[-0.016, 1.122, 0.631]}
              >
                <SpecialMaterial />
              </mesh>
              <mesh
                name="Wing8_FinalDJI_0261"
                castShadow
                receiveShadow
                geometry={nodes.Wing8_FinalDJI_0261.geometry}
                // material={materials["FinalDJI.006"]}
                position={[-0.016, 1.122, 0.631]}
              >
                <SpecialMaterial />
              </mesh>
              <mesh
                name="Wing8_FinalDJI_0262"
                castShadow
                receiveShadow
                geometry={nodes.Wing8_FinalDJI_0262.geometry}
                // material={materials["FinalDJI.006"]}
                position={[-0.016, 1.122, 0.631]}
              >
                <SpecialMaterial />
              </mesh>
              <mesh
                name="Wing8_FinalDJI_0263"
                castShadow
                receiveShadow
                geometry={nodes.Wing8_FinalDJI_0263.geometry}
                // material={materials["FinalDJI.006"]}
                position={[-0.016, 1.122, 0.631]}
              >
                <SpecialMaterial />
              </mesh>
              <mesh
                name="Wing8_FinalDJI_0264"
                castShadow
                receiveShadow
                geometry={nodes.Wing8_FinalDJI_0264.geometry}
                // material={materials["FinalDJI.006"]}
                position={[-0.016, 1.122, 0.631]}
              >
                <SpecialMaterial />
              </mesh>
              <mesh
                name="Wing8_FinalDJI_0265"
                castShadow
                receiveShadow
                geometry={nodes.Wing8_FinalDJI_0265.geometry}
                // material={materials["FinalDJI.006"]}
                position={[-0.016, 1.122, 0.631]}
              >
                <SpecialMaterial />
              </mesh>
              <mesh
                name="Wing8_FinalDJI_0266"
                castShadow
                receiveShadow
                geometry={nodes.Wing8_FinalDJI_0266.geometry}
                // material={materials["FinalDJI.006"]}
              >
                <SpecialMaterial />
              </mesh>
              <mesh
                name="Wing8_FinalDJI_0267"
                castShadow
                receiveShadow
                geometry={nodes.Wing8_FinalDJI_0267.geometry}
                // material={materials["FinalDJI.006"]}
              >
                <SpecialMaterial />
              </mesh>
              <mesh
                name="Wing8_FinalDJI_0268"
                castShadow
                receiveShadow
                geometry={nodes.Wing8_FinalDJI_0268.geometry}
                // material={materials["FinalDJI.006"]}
              >
                <SpecialMaterial />
              </mesh>
              <mesh
                name="Wing8_FinalDJI_0269"
                castShadow
                receiveShadow
                geometry={nodes.Wing8_FinalDJI_0269.geometry}
                // material={materials["FinalDJI.006"]}
              >
                <SpecialMaterial />
              </mesh>
              <mesh
                name="Wing8_FinalDJI_0270"
                castShadow
                receiveShadow
                geometry={nodes.Wing8_FinalDJI_0270.geometry}
                // material={materials["FinalDJI.006"]}
              >
                <SpecialMaterial />
              </mesh>
              <mesh
                name="Wing8_FinalDJI_0271"
                castShadow
                receiveShadow
                geometry={nodes.Wing8_FinalDJI_0271.geometry}
                // material={materials["FinalDJI.006"]}
              >
                <SpecialMaterial />
              </mesh>
              <mesh
                name="Wing8_FinalDJI_0272"
                castShadow
                receiveShadow
                geometry={nodes.Wing8_FinalDJI_0272.geometry}
                // material={materials["FinalDJI.006"]}
              >
                <SpecialMaterial />
              </mesh>
              <mesh
                name="Wing8_FinalDJI_0273"
                castShadow
                receiveShadow
                geometry={nodes.Wing8_FinalDJI_0273.geometry}
                // material={materials["FinalDJI.006"]}
              >
                <SpecialMaterial />
              </mesh>
              <mesh
                name="Wing8_FinalDJI_0274"
                castShadow
                receiveShadow
                geometry={nodes.Wing8_FinalDJI_0274.geometry}
                // material={materials["FinalDJI.006"]}
              >
                <SpecialMaterial />
              </mesh>
              <mesh
                name="Wing8_FinalDJI_0275"
                castShadow
                receiveShadow
                geometry={nodes.Wing8_FinalDJI_0275.geometry}
                // material={materials["FinalDJI.006"]}
              >
                <SpecialMaterial />
              </mesh>
              <mesh
                name="Wing8_FinalDJI_0276"
                castShadow
                receiveShadow
                geometry={nodes.Wing8_FinalDJI_0276.geometry}
                // material={materials["FinalDJI.006"]}
              >
                <SpecialMaterial />
              </mesh>
              <mesh
                name="Wing8_FinalDJI_0277"
                castShadow
                receiveShadow
                geometry={nodes.Wing8_FinalDJI_0277.geometry}
                // material={materials["FinalDJI.006"]}
              >
                <SpecialMaterial />
              </mesh>
              <mesh
                name="Wing8_FinalDJI_0278"
                castShadow
                receiveShadow
                geometry={nodes.Wing8_FinalDJI_0278.geometry}
                // material={materials["FinalDJI.006"]}
              >
                <SpecialMaterial />
              </mesh>
              <mesh
                name="Wing8_FinalDJI_0283"
                castShadow
                receiveShadow
                geometry={nodes.Wing8_FinalDJI_0283.geometry}
                // material={materials["FinalDJI.006"]}
              >
                <SpecialMaterial />
              </mesh>
              <mesh
                name="Wing8_FinalDJI_0284"
                castShadow
                receiveShadow
                geometry={nodes.Wing8_FinalDJI_0284.geometry}
                // material={materials["FinalDJI.006"]}
              >
                <SpecialMaterial />
              </mesh>
              <mesh
                name="Wing8_FinalDJI_0285"
                castShadow
                receiveShadow
                geometry={nodes.Wing8_FinalDJI_0285.geometry}
                // material={materials["FinalDJI.006"]}
              >
                <SpecialMaterial />
              </mesh>
              <mesh
                name="Wing8_FinalDJI_0286"
                castShadow
                receiveShadow
                geometry={nodes.Wing8_FinalDJI_0286.geometry}
                // material={materials["FinalDJI.006"]}
              >
                <SpecialMaterial />
              </mesh>
              <mesh
                name="Wing8_FinalDJI_0287"
                castShadow
                receiveShadow
                geometry={nodes.Wing8_FinalDJI_0287.geometry}
                // material={materials["FinalDJI.006"]}
              >
                <SpecialMaterial />
              </mesh>
              <mesh
                name="Wing8_FinalDJI_0288"
                castShadow
                receiveShadow
                geometry={nodes.Wing8_FinalDJI_0288.geometry}
                // material={materials["FinalDJI.006"]}
              >
                <SpecialMaterial />
              </mesh>
              <mesh
                name="Wing8_FinalDJI_0289"
                castShadow
                receiveShadow
                geometry={nodes.Wing8_FinalDJI_0289.geometry}
                // material={materials["FinalDJI.006"]}
              >
                <SpecialMaterial />
              </mesh>
              <mesh
                name="Wing8_FinalDJI_0290"
                castShadow
                receiveShadow
                geometry={nodes.Wing8_FinalDJI_0290.geometry}
                // material={materials["FinalDJI.006"]}
              >
                <SpecialMaterial />
              </mesh>
              <mesh
                name="Wing8_FinalDJI_0291"
                castShadow
                receiveShadow
                geometry={nodes.Wing8_FinalDJI_0291.geometry}
                // material={materials["FinalDJI.006"]}
              >
                <SpecialMaterial />
              </mesh>
              <mesh
                name="Wing8_FinalDJI_0292"
                castShadow
                receiveShadow
                geometry={nodes.Wing8_FinalDJI_0292.geometry}
                // material={materials["FinalDJI.006"]}
              >
                <SpecialMaterial />
              </mesh>
              <mesh
                name="Wing8_FinalDJI_0293"
                castShadow
                receiveShadow
                geometry={nodes.Wing8_FinalDJI_0293.geometry}
                // material={materials["FinalDJI.006"]}
              >
                <SpecialMaterial />
              </mesh>
              <mesh
                name="Wing8_FinalDJI_0294"
                castShadow
                receiveShadow
                geometry={nodes.Wing8_FinalDJI_0294.geometry}
                // material={materials["FinalDJI.006"]}
              >
                <SpecialMaterial />
              </mesh>
              <mesh
                name="Wing8_FinalDJI_0295"
                castShadow
                receiveShadow
                geometry={nodes.Wing8_FinalDJI_0295.geometry}
                // material={materials["FinalDJI.006"]}
              >
                <SpecialMaterial />
              </mesh>
              <mesh
                name="Wing8_FinalDJI_0296"
                castShadow
                receiveShadow
                geometry={nodes.Wing8_FinalDJI_0296.geometry}
                // material={materials["FinalDJI.006"]}
              >
                <SpecialMaterial />
              </mesh>
              <mesh
                name="Wing8_FinalDJI_0301"
                castShadow
                receiveShadow
                geometry={nodes.Wing8_FinalDJI_0301.geometry}
                // material={materials["FinalDJI.006"]}
              >
                <SpecialMaterial />
              </mesh>
              <mesh
                name="Wing8_FinalDJI_0302"
                castShadow
                receiveShadow
                geometry={nodes.Wing8_FinalDJI_0302.geometry}
                // material={materials["FinalDJI.006"]}
              >
                <SpecialMaterial />
              </mesh>
              <mesh
                name="Wing8_FinalDJI_0303"
                castShadow
                receiveShadow
                geometry={nodes.Wing8_FinalDJI_0303.geometry}
                // material={materials["FinalDJI.006"]}
              >
                <SpecialMaterial />
              </mesh>
              <mesh
                name="Wing8_FinalDJI_0304"
                castShadow
                receiveShadow
                geometry={nodes.Wing8_FinalDJI_0304.geometry}
                // material={materials["FinalDJI.006"]}
              >
                <SpecialMaterial />
              </mesh>
              <mesh
                name="Wing8_FinalDJI_0305"
                castShadow
                receiveShadow
                geometry={nodes.Wing8_FinalDJI_0305.geometry}
                // material={materials["FinalDJI.006"]}
              >
                <SpecialMaterial />
              </mesh>
              <mesh
                name="Wing8_FinalDJI_0306"
                castShadow
                receiveShadow
                geometry={nodes.Wing8_FinalDJI_0306.geometry}
                // material={materials["FinalDJI.006"]}
              >
                <SpecialMaterial />
              </mesh>
              <mesh
                name="Wing8_FinalDJI_0307"
                castShadow
                receiveShadow
                geometry={nodes.Wing8_FinalDJI_0307.geometry}
                // material={materials["FinalDJI.006"]}
              >
                <SpecialMaterial />
              </mesh>
              <mesh
                name="Wing8_FinalDJI_0308"
                castShadow
                receiveShadow
                geometry={nodes.Wing8_FinalDJI_0308.geometry}
                // material={materials["FinalDJI.006"]}
              >
                <SpecialMaterial />
              </mesh>
              <mesh
                name="Wing8_FinalDJI_0309"
                castShadow
                receiveShadow
                geometry={nodes.Wing8_FinalDJI_0309.geometry}
                // material={materials["FinalDJI.006"]}
              >
                <SpecialMaterial />
              </mesh>
              <mesh
                name="Wing8_FinalDJI_0310"
                castShadow
                receiveShadow
                geometry={nodes.Wing8_FinalDJI_0310.geometry}
                // material={materials["FinalDJI.006"]}
              >
                <SpecialMaterial />
              </mesh>
              <mesh
                name="Wing8_FinalDJI_0311"
                castShadow
                receiveShadow
                geometry={nodes.Wing8_FinalDJI_0311.geometry}
                // material={materials["FinalDJI.006"]}
              >
                <SpecialMaterial />
              </mesh>
              <mesh
                name="Wing8_FinalDJI_0312"
                castShadow
                receiveShadow
                geometry={nodes.Wing8_FinalDJI_0312.geometry}
                // material={materials["FinalDJI.006"]}
              >
                <SpecialMaterial />
              </mesh>
              <mesh
                name="Wing8_FinalDJI_0314"
                castShadow
                receiveShadow
                geometry={nodes.Wing8_FinalDJI_0314.geometry}
                // material={materials["FinalDJI.006"]}
              >
                <SpecialMaterial />
              </mesh>
              <mesh
                name="Wing8_FinalDJI_0315"
                castShadow
                receiveShadow
                geometry={nodes.Wing8_FinalDJI_0315.geometry}
                // material={materials["FinalDJI.006"]}
              >
                <SpecialMaterial />
              </mesh>
              <mesh
                name="Wing8_FinalDJI_0316"
                castShadow
                receiveShadow
                geometry={nodes.Wing8_FinalDJI_0316.geometry}
                // material={materials["FinalDJI.006"]}
              >
                <SpecialMaterial />
              </mesh>
              <mesh
                name="Wing8_FinalDJI_0317"
                castShadow
                receiveShadow
                geometry={nodes.Wing8_FinalDJI_0317.geometry}
                // material={materials["FinalDJI.006"]}
              >
                <SpecialMaterial />
              </mesh>
              <mesh
                name="Wing8_FinalDJI_0318"
                castShadow
                receiveShadow
                geometry={nodes.Wing8_FinalDJI_0318.geometry}
                // material={materials["FinalDJI.006"]}
              >
                <SpecialMaterial />
              </mesh>
              <mesh
                name="Wing8_FinalDJI_0319"
                castShadow
                receiveShadow
                geometry={nodes.Wing8_FinalDJI_0319.geometry}
                // material={materials["FinalDJI.006"]}
              >
                <SpecialMaterial />
              </mesh>
              <mesh
                name="Wing8_FinalDJI_0320"
                castShadow
                receiveShadow
                geometry={nodes.Wing8_FinalDJI_0320.geometry}
                // material={materials["FinalDJI.006"]}
              >
                <SpecialMaterial />
              </mesh>
              <mesh
                name="Wing8_FinalDJI_0321"
                castShadow
                receiveShadow
                geometry={nodes.Wing8_FinalDJI_0321.geometry}
                // material={materials["FinalDJI.006"]}
              >
                <SpecialMaterial />
              </mesh>
              <mesh
                name="Wing8_FinalDJI_0322"
                castShadow
                receiveShadow
                geometry={nodes.Wing8_FinalDJI_0322.geometry}
                // material={materials["FinalDJI.006"]}
              >
                <SpecialMaterial />
              </mesh>
              <mesh
                name="Wing8_FinalDJI_0323"
                castShadow
                receiveShadow
                geometry={nodes.Wing8_FinalDJI_0323.geometry}
                // material={materials["FinalDJI.006"]}
              >
                <SpecialMaterial />
              </mesh>
              <mesh
                name="Wing8_FinalDJI_0324"
                castShadow
                receiveShadow
                geometry={nodes.Wing8_FinalDJI_0324.geometry}
                // material={materials["FinalDJI.006"]}
              >
                <SpecialMaterial />
              </mesh>
              <mesh
                name="Wing8_FinalDJI_0357"
                castShadow
                receiveShadow
                geometry={nodes.Wing8_FinalDJI_0357.geometry}
                // material={materials["FinalDJI.006"]}
              >
                <SpecialMaterial />
              </mesh>
              <mesh
                name="Wing8_FinalDJI_0358"
                castShadow
                receiveShadow
                geometry={nodes.Wing8_FinalDJI_0358.geometry}
                // material={materials["FinalDJI.006"]}
              >
                <SpecialMaterial />
              </mesh>
              <mesh
                name="Wing8_FinalDJI_0359"
                castShadow
                receiveShadow
                geometry={nodes.Wing8_FinalDJI_0359.geometry}
                // material={materials["FinalDJI.006"]}
              >
                <SpecialMaterial />
              </mesh>
              <mesh
                name="Wing8_FinalDJI_0360"
                castShadow
                receiveShadow
                geometry={nodes.Wing8_FinalDJI_0360.geometry}
                // material={materials["FinalDJI.006"]}
              >
                <SpecialMaterial />
              </mesh>
              <mesh
                name="Wing8_FinalDJI_0361"
                castShadow
                receiveShadow
                geometry={nodes.Wing8_FinalDJI_0361.geometry}
                // material={materials["FinalDJI.006"]}
              >
                <SpecialMaterial />
              </mesh>
              <mesh
                name="Wing8_FinalDJI_0362"
                castShadow
                receiveShadow
                geometry={nodes.Wing8_FinalDJI_0362.geometry}
                // material={materials["FinalDJI.006"]}
              >
                <SpecialMaterial />
              </mesh>
              <mesh
                name="Wing8_FinalDJI_0363"
                castShadow
                receiveShadow
                geometry={nodes.Wing8_FinalDJI_0363.geometry}
                // material={materials["FinalDJI.006"]}
              >
                <SpecialMaterial />
              </mesh>
              <mesh
                name="Wing8_FinalDJI_0365"
                castShadow
                receiveShadow
                geometry={nodes.Wing8_FinalDJI_0365.geometry}
                // material={materials["FinalDJI.006"]}
                position={[2.053, 1.579, 0.786]}
                rotation={[-3.12, 0.001, -3.027]}
              >
                <SpecialMaterial />
              </mesh>
              <mesh
                name="Wing8_FinalDJI_0435"
                castShadow
                receiveShadow
                geometry={nodes.Wing8_FinalDJI_0435.geometry}
                // material={materials["FinalDJI.006"]}
                position={[1.539, 1.065, -2.254]}
                rotation={[3.022, -0.014, -2.903]}
              >
                <SpecialMaterial />
              </mesh>
              <mesh
                name="Wing8_FinalDJI_0476"
                castShadow
                receiveShadow
                geometry={nodes.Wing8_FinalDJI_0476.geometry}
                // material={materials["FinalDJI.006"]}
                position={[-1.539, 1.065, -2.254]}
                rotation={[3.022, 0.014, 2.903]}
              >
                <SpecialMaterial />
              </mesh>
              <mesh
                name="Wing8_FinalDJI_0514"
                castShadow
                receiveShadow
                geometry={nodes.Wing8_FinalDJI_0514.geometry}
                // material={materials["FinalDJI.006"]}
                position={[-2.084, 1.572, 0.786]}
                rotation={[-3.12, 0.077, 3.025]}
              >
                <SpecialMaterial />
              </mesh>
            </group>
          </group>
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/assets/models/dji-mavic-2-pro/DJI-Mavic-Pro-2S-1k.glb");

export default Model;
