/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

import HolographicMaterial from "./HolographicMaterial";

const holographicControls = {
  fresnelAmount: { value: 0.45, min: 0.0, max: 1.0, label: "Fresnel Amount" },
  fresnelOpacity: {
    value: 1.0,
    min: 0.0,
    max: 1.0,
    label: "Fresnel Opacity",
  },
  scanlineSize: { value: 8.0, min: 1.0, max: 15, label: "Scanline size" },
  hologramBrightness: { value: 1.2, min: 0.0, max: 2, label: "Brightness" },
  signalSpeed: { value: 0.45, min: 0.0, max: 2, label: "Signal Speed" },
  hologramOpacity: { value: 1.0, min: 0.0, max: 1.0, label: "Holo Opacity" },
  hologramColor: { value: "#51a4de", label: "Holo Color" },
  enableBlinking: true,
  blinkFresnelOnly: true,
  enableAdditive: true,
  enabled: true,
  Model: { options: ["VADER", "BB8", "WALKER"] },
  side: { options: ["FrontSide", "BackSide", "DoubleSide"] },
};

export function Model(props) {
  const { nodes, materials } = useGLTF(
    "/assets/models/dji-mavic-2-pro/DJI-Mavic-Pro-2S.glb"
  );
  return (
    <group {...props} dispose={null}>
      <group name="Scene">
        <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]}>
          <group name="Finalfbx" rotation={[Math.PI / 2, 0, 0]}>
            <group name="RootNode">
              <group name="Wing8">
                <mesh
                  name="Wing8_FinalDJI_0"
                  castShadow
                  //receiveShadow
                  geometry={nodes.Wing8_FinalDJI_0.geometry}
                  // position={[0, 0, 0]}
                  // material={materials.FinalDJI}
                >
                  <HolographicMaterial />
                </mesh>
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/assets/models/dji-mavic-2-pro/DJI-Mavic-Pro-2S.glb");

export default Model;
