/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function Model(props) {
  const { nodes, materials } = useGLTF(
    "/assets/models/dji-mavic-2-pro/DJI-Mavic-Pro-2S.glb"
  );
  return (
    <group {...props} dispose={null}>
      <group name="Scene">
        <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]}>
          <group name="Finalfbx" rotation={[Math.PI / 2, 0, 0]}>
            <group name="RootNode">
              <group name="Wing8">
                <mesh
                  name="Wing8_FinalDJI_0"
                  castShadow
                  receiveShadow
                  geometry={nodes.Wing8_FinalDJI_0.geometry}
                  material={materials.FinalDJI}
                />
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/assets/models/dji-mavic-2-pro/DJI-Mavic-Pro-2S.glb");

export default Model;
